TID-Lab/aggie

- public/angular/js/controllers/incidents/index.js
- public/angular/js/controllers/reports/index.js
- public/angular/templates/incidents/index.html
- public/angular/templates/reports/index.html
Added button to remove any filter applied (not including search string). Button hides if no filters are currently applied.
> 1287 feature clear filters

- lib/api/socket-handler.js
- public/angular/js/controllers/trends/index.js
- public/angular/js/services/socket.js
I think this fix should also address #1880.
> issue #1879 - fixed accumulative trend events

- public/angular/css/loading-bar.css
- public/angular/index.html
- public/angular/js/app.js
- public/angular/js/controllers/reports/show.js
- public/angular/js/loading-bar.js
- public/angular/js/routes.js
Tom please review this. I kept it very simple. The loading indicator is based on:
https://github.com/chieffancypants/angular-loading-bar 
I had to refactor router a bit and moved `report` to `resolve` section.
> #1407 - setup loading indicator; refactored router

- README.md
- migrations/.migrate
- migrations/1421074933099-update-idnum-in-incidents.js
- models/incident.js
- models/query/incident-query.js
- package.json
- public/angular/js/controllers/incidents/form_modal.js
- public/angular/js/controllers/incidents/index.js
- public/angular/js/routes.js
- public/angular/js/services/map.js
- public/angular/templates/incidents/index.html
- public/angular/templates/incidents/modal.html
- public/angular/templates/incidents/show.html
- shared/incident.js
- test/lib.api.v1.incident-controller.test.js
- test/models.query.incident-query.test.js
I introduced db migrations based on https://github.com/tj/node-migrate
in order to run outstanding migrations you can run:
````bash
migrate up
`````
> 1892 new incident structure

- public/angular/js/app.js
- public/angular/js/controllers/users/form_modal.js
- public/angular/js/directives/aggie-username.js
- public/angular/templates/users/modal.html
Username must be less than 15 chars, and only contain alphanumeric  characters or the underscore.
> Bug #1779 Username limitation on user creation

- lib/api/v1/incident-controller.js
- models/incident.js
- models/report.js
- package.json
- public/angular/index.html
- public/angular/js/app.js
- public/angular/js/controllers/incidents/index.js
- public/angular/js/controllers/reports/show.js
- public/angular/js/directives/ng-select-all.js
- public/angular/js/filters/interval.js
- public/angular/js/filters/tripledigit.js
- public/angular/js/services/incident.js
- public/angular/sass/app.scss
- public/angular/sass/tables.scss
- public/angular/templates/incidents/index.html
- public/angular/templates/reports/table.html
- test/lib.api.v1.incident-controller.test.js
http://redmine.sassafras.coop/issues/1897
> 1897 incident table changes

- lib/api/v1/report-controller.js
- models/batch.js
- models/report.js
- public/angular/js/app.js
- public/angular/js/controllers/incidents/form_modal.js
- public/angular/js/controllers/incidents/report_incident_modal.js
- public/angular/js/controllers/reports/index.js
- public/angular/js/routes.js
- public/angular/js/services/batch.js
- public/angular/js/services/incident.js
- public/angular/js/services/report.js
- public/angular/sass/app.scss
- public/angular/sass/tables.scss
- public/angular/templates/incidents/index.html
- public/angular/templates/reports/batch.html
- public/angular/templates/reports/index.html
- public/angular/templates/reports/table.html
- test/lib.api.v1.report-controller.test.js
- test/models.batch.test.js
- test/models.report.test.js
http://redmine.sassafras.coop/issues/1900
> 1900 batch mode

- lib/api/v1/incident-controller.js
- lib/database.js
- models/incident.js
- public/angular/templates/incidents/index.html
- public/angular/templates/incidents/show.html
http://redmine.sassafras.coop/issues/1746
> 1746 - added creator to incidents

- lib/api.js
- lib/api/socket-handler.js
- lib/api/streamer.js
- models/incident.js
- models/report.js
- public/angular/js/controllers/reports/index.js
- public/angular/js/services/queue.js
http://redmine.sassafras.coop/issues/1763
> 1763 stream updates

- README.md
- config/secrets.json.example
- package.json
Adds installation instructions. Also adds information about APIs and sources for configuring feed.
> 1245 documentation

- README.md
> Complete testing instructions

- package.json
- test/lib.api.socket-handler.test.js
> Get socket.io-client from the official package.

- public/angular/js/controllers/fetching.js
- public/angular/templates/settings.html
Switch to set the fetching state changes the state automatically without need to push the Save button, which has been removed
> 4137: Removed button to save settings and refactored fetching controller

- lib/api/v1/settings-controller.js
- lib/fetching/content-services/test-content-services.js
- public/angular/js/controllers/media/settings/settings_modal.js
- public/angular/js/services/settings.js
- public/angular/templates/media/settings/modal.html
- test/lib.api.v1.settings-controller.test.js
The settings modal has one Test button for the purpose
> 4155: Settings for source types can now be tested online

- .gitignore
- README.md
- lib/api.js
- lib/api/socket-handler.js
- package.json
- test/init.js
- test/lib.api.socket-handler.test.js
- test/lib.process-manager.test.js
HTTPS now is the only way to access Aggie. Important when API credential information is transmitted between client and server.
> 4187 https support

- README.md
- config/secrets.js
- config/secrets.json.example
- lib/api/v1/settings-controller.js
- lib/fetching/content-services/test-content-services.js
- public/angular/js/app.js
- public/angular/js/config.js
- public/angular/js/controllers/media/settings.js
- public/angular/js/controllers/media/settings/settings_modal.js
- public/angular/js/filters/capitalize.js
- public/angular/js/filters/clean-settings.js
- public/angular/js/services/fetching.js
- public/angular/js/services/media_modal.js
- public/angular/js/services/settings.js
- public/angular/sass/components/modals.scss
- public/angular/templates/media/settings/modal.html
- public/angular/templates/settings.html
- shared/user.js
- test/lib.api.v1.settings-controller.test.js
No need to edit the config file for media settings. Configuration still in file but should be moved to db. Only admin users can change the settings in the app. README updated with new instructions
Interactive test of settings not ready.
> 4000: Media settings can be set up online within aggie application

- npm-shrinkwrap.json
Lock down dependency versions for repeatable testing.
> Shrinkwrap dependencies

- lib/api.js
- public/angular/js/controllers/media/settings.js
- public/angular/templates/settings.html
HTTPS server is not created if no certs are found. Instead normal HTTP
is created.
Admin is informed in the settings page.
> 4396: Http server is created if not certs

- lib/api/reset-password.js
- lib/api/v1/user-controller.js
- lib/mailer.js
Links in emails now get either "http" or "https" as appropriate.
> 4486 Links sent in emails have variable protocols

- public/angular/index.html
- public/angular/js/controllers/incidents/form_modal.js
Solution here:
https://github.com/wpalahnuk/ngAutocomplete/issues/62
> 4597: Fixed bug

- lib/api/authorization.js
- lib/api/v1/incident-controller.js
- lib/api/v1/report-controller.js
- lib/api/v1/source-controller.js
- lib/api/v1/user-controller.js
- migrations/.migrate
- migrations/1468989776640-change-manager-role-to-monitor.js
- public/angular/js/config.js
- public/angular/js/controllers/navbar.js
- public/angular/js/services/auth.js
- public/angular/templates/incidents/index.html
- public/angular/templates/incidents/show.html
- public/angular/templates/incidents/table.html
- public/angular/templates/navbar.html
- public/angular/templates/reports/index.html
- public/angular/templates/reports/table.html
- public/angular/templates/sources/index.html
- public/angular/templates/trends/bars.html
- public/angular/templates/trends/lines.html
- public/angular/templates/users/index.html
- public/angular/translations/locale-en.json
- public/angular/translations/locale-es.json
- shared/user.js
Implemented authorization as per 
https://docs.google.com/spreadsheets/d/1Rv_SMIKfNhv4yIDWsJ6ibESKlRcQXa1rUieE1hSu1hk/edit#gid=0
In the process:
Simplified permissions
Tweaked UI for viewers
Special arrangements done to allow for viewers and monitors to modify their user information
> 1785 api authorization

- public/angular/templates/incidents/report_incident_modal.html
To reproduce the bug this fixes:
1. From reports page click add in the incident column [modal should
appear]
> Fix malformed string

- test/lib.fetching.content-services.elmo-content-service.test.js
- test/lib.fetching.content-services.facebook-content-service.test.js
I left this out of the last commit! PR #176 was broken.
> Hotfix for cleaning init.js

- lib/fetching.js
- lib/fetching/bot-master.js
- test/backend/lib.fetching.content-services.smsgh-content-service.test.js
- test/end-to-end/duplication.test.js
- test/end-to-end/e2e-tools.js
- test/end-to-end/login.test.js
- test/end-to-end/protractor.conf.js
- test/end-to-end/source-fetching-toggle.test.js
This contains a fix for the duplication of reports that was occurring in Twitter and SMSGh (noticed). There were two listeners for the same events, leading to duplication. There is still possibility of discovering a bug related to this in the future: there is a listener for all events emitted by the API process, but only for 1 event emitted by the Fetching process. But currently, this code fixes the known bugs related to this code. The changes to bot-master.js have been made to mimic Andres' PR (PR 171).
This also contains an end-to-end test to check how Aggie reacts to different states of Fetching and Sources.
> 5043 Duplication bug is fixed

- lib/api/v1/incident-controller.js
- public/angular/js/controllers/incidents/show.js
- public/angular/js/controllers/reports/index.js
- public/angular/js/filters/capitalize.js
- test/backend/lib.api.v1.incident-controller.test.js
Fixes four bugs:
1958: Clicking flag in incident-show does not work
5147: Adding report to incident from batch doesn't update table
4933: Mark All: "Cannot read property 'charAt' of undefined"
1949: Multiple incident delete failing
> Small and urgent bugs

- public/angular/js/controllers/sources/index.js
This now contains the keyword the source is listening to.
> bug-fix 5243: target field in sources page for SMSGH source

- lib/analytics/trend-master.js
- lib/api.js
- lib/fetching/bots/pull-bot.js
- lib/fetching/content-services/rss-content-service.js
- lib/process-manager.js
- models/incident.js
- models/source.js
- models/user.js
Normal usage does not seem to trigger this error. So, if triggered, it is something serious.
Logger will, therefore, report it as an error.
> 4802: Added error handling for Incident update

- npm-shrinkwrap.json
- package.json
- test/end-to-end/smsgh.test.js
This test does the following
1. Make an SMS GH source
2. Generate 1 report from it [OK]
3. Delete the source
4. Make an SMS GH source
5. Generate 1 more SMS GH report [doesn't appear]
This test reuses a bit of code from `source-fetching-toggle.test.js`,
and these two should probably be worked together in some way.
> 5285 This test deletes and creates a new SMS GH source

- lib/fetching/content-services/facebook-content-service.js
- lib/fetching/content-services/twitter-content-service.js
- models/report.js
- test/backend/fixtures/facebook-1.json
- test/backend/fixtures/facebook-2.json
- test/backend/lib.fetching.content-services.facebook-content-service.test.js
Save metadata from twitter, facebook for post-hoc analysis.
> 5357 metadata

- lib/fetching/content-services/facebook-content-service.js
> 5304: Looking for errors from FBgraph and downgrading them to warmings

- README.md
- config/secrets.json.example
- lib/api/v1/incident-controller.js
- lib/api/v1/report-controller.js
- lib/api/v1/source-controller.js
- lib/logger.js
- lib/userLogger.js
- lib/writeLog.js
Log user interaction with Aggie. Storing actions like:
Reports read/flagged
Report added to incident
Incident created/edited/viewed
Source created/edited/deleted
> 5356 logging

- migrations/1479715263462-source-string-to-sources-array.js
> Latest migration uses a streaming update

- migrations/1479715263462-source-string-to-sources-array.js
The previous PR for this migration made it nice and fast, but broke some
conditionals so nothing was actually being changed! If only we could
test migrations automatically...
The migration is still nice and fast :)
> _sources migration actually makes changes now

- migrations/1479715263462-source-string-to-sources-array.js
The previous PR for this migration made it nice and fast, but broke some
conditionals so nothing was actually being changed! If only we could
test migrations automatically...
The migration is still nice and fast :)
> _sources migration actually makes changes now (#234)

- lib/fetching/content-services/facebook-content-service.js
- test/backend/fixtures/facebook-1.json
- test/backend/fixtures/facebook-2.json
In addition, storing the post's external link, if present, as metadata.
> Storing post URL for Facebook sources

- diff
- docs/content/installation.md
- docs/content/intro/collaborations.md
- docs/content/intro/introduction.md
- docs/content/settings/settings.md
- docs/content/smtc/smtc.md
- docs/content/usermanagement/usermanagement.md
- docs/content/usingaggie/usingaggie.md
- docs/index.rst
- karma.conf.js
- lib/api.js
- lib/api/v1/incident-controller.js
- lib/fetching/content-services/twitter-content-service.js
- migrations/1479715263462-source-string-to-sources-array.js
- models/incident.js
- models/query/report-query.js
- models/to-regexp.js
- npm-shrinkwrap.json
- package.json
- public/angular/js/controllers/login.js
- public/angular/js/services/socket.js
- public/angular/sass/components/tables.scss
- public/angular/templates/reports/index.html
- public/angular/templates/reports/table.html
* Tag filters ignore case (#236)
* Hitting enter no longer cancels password set (#243)
* Tag column isn't too wide (#244)
* Stats bar appears (#245)
* Monitors can create incidents (#246)
> Update deployment server with latest changes

- lib/api/v1/source-controller.js
- public/angular/templates/sources/index.html
- public/angular/templates/sources/show.html
- shared/user.js
Added a new 'edit sources' permission.
Update controller and frontend so only admins edit sources and see the
UI elements for it.
I can't make non-admin users locally so I have no idea if this works yet D:
> 5542 Only admins can edit sources

- lib/fetching/content-services/twitter-content-service.js
- public/angular/sass/components/tables.scss
- public/angular/templates/reports/batch.html
- public/angular/templates/reports/table.html
Also align the 2nd set of batch buttons to the right.
> Display multiple twitter sources

- public/angular/js/app.js
- public/angular/js/controllers/password_reset_admin.js
- public/angular/translations/locale-en.json
- test/end-to-end/e2e-tools.js
Also make sure admin logs in again with the new password to make sure the
session is in good state.
End-to-end test behaviour adapted to previous point.
> 7302: Make angular app listen to $stateChangeError

- public/angular/js/controllers/incidents/report_incident_modal.js
- public/angular/templates/incidents/report_incident_modal.html
Bringing commit from Ghana Deployment  with some small fixes
> 7402 pagination report incident modal

- public/angular/js/controllers/reports/index.js
- public/angular/js/filters/delay.js
- public/angular/sass/shared/buttons.scss
- public/angular/templates/reports/table.html
- public/angular/templates/users/modal.html
- public/angular/templates/users/profile.html
- public/angular/translations/locale-en.json
- public/angular/translations/locale-es.json
- test/backend/public.angular.translations.test.js
Building on 5543, created the Spanish translation. Small changes to code and UI to accommodate for potentially larger strings.
> Aggie is now translated to Spanish
