- models/incident.js
- models/source.js
- package.json
- test/lib.api.v1.source-facebook-controller.test.js
- test/models.source.test.js
In the legacy version of `mongoose-validator`, `validate('max', 20)` would fail on strings that begin with a number greater than 20. Updating `mongoose-validator` solves this.
> 4208 allow numbers in nicknames

- test/lib.process-manager.test.js
Due to a storm of side effects from other tests, the final test in this
suite was passing `npm test` when it should have been failing. Two of
the lines in this change implement the fix to make this test suite run
successfully in isolation--the others are just for clarity.
1. `+require('./init');`
Gotta connect to the database.
2. Replace `type` with `media`
Type was renamed to media as of 35fd74
> Fix up process manager tests

- test/manual/fetching.load.test.js
- test/manual/query-reports.load.test.js
For the test to pass when run with default settings and no manual
handling of environment variables, a few tweaks are needed. Namely, URLs
need to change from `http` to `https`, and the environment variable
`NODE_TLS_REJECT_UNAUTHORIZED` needs to be false.
> Update the manual tests for https

- README.md
- docker/Dockerfile
- docker/docker-compose.yml
- install.js
- lib/api/authentication.js
- lib/database.js
- package.json
- test/init.js
Dockerfile and docker-compose used to ease deployment of single
instance of aggie. To test, run in docker folder:
```docker-compose up```
This will set up Aggie at `https://localhost`.
`node install.js` is now run before `npm test` and `npm start`, rather
than after `npm install`, which may be a minor inconvenience to those
running without docker.
> Dockerize aggie

- lib/api/v1/report-controller.js
- public/angular/js/controllers/incidents/form_modal.js
- public/angular/js/controllers/incidents/report_incident_modal.js
- public/angular/js/controllers/reports/index.js
- public/angular/templates/incidents/report_incident_modal.html
- public/angular/templates/reports/table.html
Now Adding an incident to a single or multiple report works better. Incident can be a new one or an old one. Newly created incidents are fetched so that linked reports show the incident title without the need for a browser refresh.
This also fixes Bug #4599: Should not be redirecting to incident page when creating incident via report page
> 4599 add incident from report page

- models/incident.js
- test/lib.api.v1.report-controller.test.js
Linking reports to incident fired consecutives db finds to the same incident which updated the values in the callback. Now, we use atomic call findByIdAndUpdate.
Added test to check fix.
> 4797: Fixed raced condition when increasing totalReports

- lib/fetching.js
Now `_addSourceListeners` will get called with `emitter` as the
`Source.schema` from the fetching process. This is also kind of silly
because it goes through ChildProcess unnecessarily, but it seems clean
enough.
This PR is instead of #171
> 4602 source errors not disabling: alternate fix

- public/angular/js/controllers/users/form_modal.js
- public/angular/templates/users/modal.html
Summary: Subtly poor coding practices from long ago became a bug when
internationalization was added.
To reproduce the bug this fixes, go to `/users`, click the pencil by
your user, and click the Change Password button. This button wasn't
doing anything.
The cause was that adding the `translate` directive to the element
creates a new child scope. When the `ng-click` directive tried to update
the `showPassword` model it was only changing on the child scope. Best
practice is for `$scope` to always hold a reference to an object that
holds the primitives that make up the model. Then the object can be
shared between parent and child scopes. See
https://github.com/angular/angular.js/wiki/Understanding-Scopes
I read through the rest of the internationalization changes and it
seems this is the …
> Bugfix for change password button

- public/angular/js/services/flash.js
To reproduce the bug this fixes:
1. Go to Settings > Settings
2. Click Edit in the email transport field
3. Click Submit in the modal that pops up
The notice "SES setting has been successfully saved." should appear, but
it was only saying " setting has been successfully saved."
> Pass params to be interpolated in flash alerts

- public/angular/templates/incidents/report_incident_modal.html
- public/angular/templates/reports/table.html
PR #169 for 4599 removed the alternate "Add", and then PR #167 for 1785 added it back in improperly.
This fix leaves a bit to be desired, but it is very small and solves both of these bugs. Optimally, we would still use the `IncidentFormModalController` when there are no incidents yet. Adapting this modal for the reports page would take some extra work, however.
> 4943 and 4939 Add button appearing twice and report redirection.

- package.json
- public/angular/js/app.js
- public/angular/js/translations.js
- public/angular/templates/incidents/show.html
- public/angular/translations/locale-en.json
If angular translate (through the directive, filter, immediate, etc.) is
passed a translation ID that can't be found, it will now log an error
to the browser's debug console.
This adds a handful of those missing translations and fixes a
bug in one translation.
> 4932 missing strings

- lib/fetching/bots/subscribe-bot.js
- lib/fetching/content-services/smsgh-content-service.js
- test/backend/lib.fetching.content-services.smsgh-content-service.test.js
smsgh-content-service's unsubscribe function now closes the server when no sources are subscribed. It also throws a warning when unsubscribe() is called for a source that isn't subscribed in the first place.
The test has been modified accordingly (argument passed to the unsubscribe function), and all tests are now passing.
> 5121 smsgh-content-service unsubscribe functionality

- lib/fetching/content-services/facebook-content-service.js
- test/backend/fixtures/facebook-3.json
- test/backend/init.js
- test/backend/lib.fetching.content-services.facebook-content-service.test.js
A list of transient errors has been created from https://developers.facebook.com/docs/graph-api/using-graph-api/#errors. Experience may lead us to change that list as time evolves.
Comes with a test!
> 4496: Specific facebook error codes emit warnings rather than errors

- README.md
- package.json
- test/end-to-end/e2e-tools.js
- test/end-to-end/with-apis/README.md
- test/end-to-end/with-apis/protractor.conf.js
- test/end-to-end/with-apis/source-fetching-toggle.twitter.test.js
These tests require access to the Twitter API, so we've added a new
command `npm run protractor-with-apis` which is documented in
`test/end-to-end/with-apis/README.md`.
Four tests are added here. The first two are passing, and the second two
are failing.
These tests all pass on the current 5102_fetching_reliability:
```
git checkout 4544ab9c2
git cherry-pick 6f5c896
npm i
npm run testrun &
npm run protractor-with-apis
```
> 5102 A couple tests for the fetching toggling issue

- lib/analytics/trend-queryer.js
- models/report.js
- npm-shrinkwrap.json
- package.json
The very old `mongoose-text-search` plugin was using deprecated functionality in mongo. Now it's gone and we're closer to being able to upgrade mongo.
This is created from the 5052 branch, which took the first step of removing some of our calls to the text search plugin.
> 1927 remove Mongo text search

- test/end-to-end/e2e-tools.js
- test/end-to-end/source-fetching-toggle.test.js
This prevents warnings from cluttering the terminal window where the tests are running.
> Current e2e tests choose the first element (where applicable) explicitly

- models/incident.js
- test/backend/lib.api.v1.incident-controller.test.js
Proposal for tag field in schema
Simple array of strings. It should be easy and fast to search through them.
We don't know how we are going to get tags passed by the front end to the IncidentQuery, and some though and tests are required at both ends.
> 5326: Added tags to Incident schema as an array of strings

- lib/fetching/bot.js
- models/source.js
- public/angular/js/controllers/sources/index.js
- test/end-to-end/e2e-tools.js
- test/end-to-end/with-apis/facebook-error.test.js
The source schema in the fetching process gets out of date when clicking
'On' or 'Off' from `/sources`. Only the `source:save` event triggers
reloading the source, not `source:enable` or `source:disable`. Now we
emit `source:save` whenever a source is saved.
Two other changes here that I ran into
* in `bot.js`, `logEvent` sends its errors to the
callback, which should not be ignored.
* `$scope.refresh` from `SourcesIndexController` is not used anywhere
> 4803 When sources error, the fetching button turns off

- models/incident.js
- models/query/incident-query.js
- test/backend/models.query.incident-query.test.js
Server-side code for filtering incidents by tags.
If a single tag is provided, all incidents with that tag are shown.
If multiple tags are provided, all incidents that contain `at least 1` of those tags are shown.
> 5330: Filtering incidents by tags

- public/angular/.eslintrc.json
- public/angular/js/app.js
- public/angular/js/controllers/incidents/form_modal.js
- public/angular/js/controllers/incidents/index.js
- public/angular/js/routes.js
- public/angular/js/services/tags.js
- public/angular/templates/incidents/modal.html
- public/angular/templates/incidents/table.html
The incident modal now has a field to add a list of tags to an incident (id is `tags`), and the table at `/incidents` has a column for an incident's tags. Also resolves 5328.
> 5327 add tag to incident

- lib/api/v1/incident-controller.js
- models/incident.js
- public/angular/js/controllers/incidents/form_modal.js
- public/angular/js/routes.js
- public/angular/js/services/tags.js
- shared/incident.js
- test/backend/models.query.incident-query.test.js
Fixes some bugs from #209, #210, #211, #213 so that filtering incidents by tags works. This passes the tests in #214.
> Filter incident by tags

- lib/fetching/content-services/smsgh-content-service.js
- test/backend/lib.fetching.content-services.smsgh-content-service.test.js
Emitting SMS reports with keyword lowercased
Both the source-identifier and request's keyword are different cases
`getKeyword` function ensures uniformity between request's keyword and source's keyword
Fixed merge conflicts, replacing #227
> 5422 smsgh case handling

- lib/userLogger.js
There are some user actions that trigger more than one user log action at the same time. For example, adding a report to an incident (involving creating an incident) first creates the incident, and immediately adds the report to an incident. With the unique property, there were errors as these actions used to occur within the same millisecond.
> Removed unique property for indexing user logs

- public/angular/templates/reports/batch.html
As Tom said in #129, "The 'xx new reports have arrived'
bar should not show up when in batch mode."
> Don't show new reports notification in batch mode

- public/angular/templates/choose_password.html
Turns out button elements without a `type="button"` are `type="submit"` by default!
Fixed that.
> Enter no longer cancels the password change

- karma.conf.js
- public/angular/js/controllers/login.js
- public/angular/js/services/socket.js
The stats bar wasn't getting populated upon logging in because it was
trying to use the socket that was created when the page was loaded, at
which point the user wasn't authenticated.
> 4459 Recreate the socket after logging in

- lib/api/v1/incident-controller.js
Creating an incident had been using the 'edit incidents' permission
which is not defined in `shared/user.js`.
> Create incident uses 'edit data' permission

- shared/user.js
There was no permissions allotted for 'manage trends', and therefore, monitors could not create trends. This has been fixed.
> Monitors can create/edit/delete trends

- public/angular/js/controllers/reports/index.js
Filtering reports uses the query string, and filtering incidents uses
the request body. Grabbing a batch uses the request body, so we pass an
array. If only this were standardized!
> 5539 Convert tags to array for grab batch with tags

- lib/fetching/bot.js
- lib/fetching/content-services/facebook-content-service.js
Since Twitter has an RT and NO_RT tag added, I feel it's required for Facebook as well, given that sometimes comments might not be as useful as posts to get relevant information.
So, I've followed Andrés' model on adding the twitter RT|NO_RT tag, and done the same for Facebook.
> Added comment/post tag to Facebook reports

- lib/api/v1/report-controller.js
- lib/api/v1/trend-controller.js
- lib/writeLog.js
- Media of source/report touched added to user logs
- Storing more information when an incident is created/edited
- The filter in place for a user
- Grab batch
This PR can be kept open until the last moment, and all addition fields can be added to this branch, and later merged.
> Adding additional fields to make userlogs more useful

- public/angular/js/routes.js
Grab batch will apply a filter you have set up, but when clicking Mark
All Read & Grab Another, Aggie was forgetting about the tags part of the
filter.
> Apply tag filter with Grab Another

- lib/fetching/content-services/replay-content-service.js
- models/batch.js
- npm-shrinkwrap.json
- package.json
- test/backend/models.batch.test.js
MongoDB does not have support for atomic updates of batches. While we move to
some other DB, a locking mechanism is put in place to make sure that reports are
only checked out by one user at a time.
> 5584: Locking a batch is now atomic using read/write lock
